name: lineplot

on:
  push:
    paths:
      - 'swedbank.csv'
jobs:
  generate-lineplot:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r env/requirements.txt

      - name: generate lineplot
        run: python bin/lineplot.py

      - name: commit & push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add images/lineplot.png
          git commit -m "Update lineplot.png"
          git push