name: check homepage

on:
  schedule:
    - cron: '0 10,17 * * 1-5' # mon - fri @ 10 am & 5 pm (bank hours)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    
    - name: check homepage
      run: |
        python webscrape.py